export const players = [
  {
    imgHero: "../assets/images/images-card/zarya-wallpaper.png",
    name: "Leonardo Rezio",
    nick: "leorezio ",
    role: ["cardtank", "../assets/images/Icons/tnk-azul-semborda.png"],
    instagram: "https://www.instagram.com/leorezio/",
    date: "29/12/2019",
    city: "Brasília/DF",
  },
  {
    imgHero: "../assets/images/images-card/reinhardt-wallpaper.jpg",
    name: "Lucas Braga",
    nick: "magrins_ ",
    role: ["cardtank", "../assets/images/Icons/tnk-azul-semborda.png"],
    instagram: "https://www.instagram.com/os_lcs/",
    date: "11/04/2020",
    city: "Rio de Janeiro/RJ",
  },
  {
    imgHero: "../assets/images/images-card/Hog-wallpaper.png",
    name: "Marcos Vinicius",
    nick: "mega-shockwaveee ",
    role: ["cardtank", "../assets/images/Icons/tnk-azul-semborda.png"],
    instagram: "https://www.instagram.com/marcosvii01/",
    date: "05/12/2020",
    city: "São Paulo/SP",
  },
  {
    imgHero: "../assets/images/images-card/hammond-wallpaper.png",
    name: "Fausto Cavalleiro",
    nick: "vence12345 ",
    role: ["cardtank", "../assets/images/Icons/tnk-azul-semborda.png"],
    instagram: "https://www.instagram.com/faustocmb/",
    date: "05/12/2020",
    city: "Belém/PA",
  },
  {
    imgHero: "../assets/images/images-card/tracer-wallpaper.jpg",
    name: "João Grahl",
    nick: "coffez- ",
    role: ["carddps", "../assets/images/Icons/dps-amarelo-semborda.png"],
    instagram: "#",
    date: "20/07/2020",
    city: "São Leopoldo/RS",
  },
  {
    imgHero: "../assets/images/images-card/soldier-wallpaper.jpg",
    name: "Eduardo Ferreira",
    nick: "ehusty ",
    role: ["carddps", "../assets/images/Icons/dps-amarelo-semborda.png"],
    instagram: "#",
    date: "13/12/2020",
    city: "Santo Antônio da Platina/PN",
  },
  {
    imgHero: "../assets/images/images-card/junkrat-wallpaper.jpg",
    name: "Eric Matos",
    nick: "ericmatos19 ",
    role: ["carddps", "../assets/images/Icons/dps-amarelo-semborda.png"],
    instagram: "https://www.instagram.com/_ericmatos/",
    date: "11/04/2020",
    city: "São Bernardo do Campo/SP",
  },
  {
    imgHero: "../assets/images/images-card/mccree-wallpaper.jpg",
    name: "Daniel Sette",
    nick: "settedan ",
    role: ["carddps", "../assets/images/Icons/dps-amarelo-semborda.png"],
    instagram: "https://www.instagram.com/danielsette/",
    date: "Co-Fundador",
    city: "São Paulo/SP",
  },
  {
    imgHero: "../assets/images/images-card/doomfist-wallpaper.png",
    name: "Wesley Siley",
    nick: "wellington_siley ",
    role: ["carddps", "../assets/images/Icons/dps-amarelo-semborda.png"],
    instagram: "https://www.instagram.com/sileymelo/",
    date: "30/10/2020",
    city: "Rio de Janeiro/RJ",
  },
  {
    imgHero: "../assets/images/images-card/bastion-wallpaper.jpg",
    name: "Matheus Vissentini",
    nick: "zy_ban_yz ",
    role: ["carddps", "../assets/images/Icons/dps-amarelo-semborda.png"],
    instagram: "#",
    date: "30/12/2020",
    city: "Vargem Grande Paulista/SP",
  },
  {
    imgHero: "../assets/images/images-card/ana-wallpaper.png",
    name: "",
    nick: "f3r3s__ ",
    role: ["cardsup", "../assets/images/Icons/sup-rosa-semborda.png"],
    instagram: "https://www.instagram.com/vferes_/",
    date: "25/07/2020",
    city: "Goiânia/GO",
  },
  {
    imgHero: "../assets/images/images-card/mercy-wallpaper.png",
    name: "Leandro Ferreira",
    nick: "lehboss ",
    role: ["cardsup", "../assets/images/Icons/sup-rosa-semborda.png"],
    instagram: "https://www.instagram.com/xo_lehboss/",
    date: "Fundador",
    city: "São Paulo/SP",
  },
  {
    imgHero: "../assets/images/images-card/ana-wallpaper.png",
    name: "Diana Toyama",
    nick: "littlescret__ ",
    role: ["cardsup", "../assets/images/Icons/sup-rosa-semborda.png"],
    instagram: "https://www.instagram.com/dianatoyama/",
    date: "25/07/2020",
    city: "Goiânia/GO",
  },
  {
    imgHero: "../assets/images/images-card/Baptiste-wallpaper.png",
    name: "Francisco Pimentel",
    nick: "lord_severo ",
    role: ["cardsup", "../assets/images/Icons/sup-rosa-semborda.png"],
    instagram: "https://www.instagram.com/insta.chico_/",
    date: "07/07/2029",
    city: "Recife/PE",
  },
  {
    imgHero: "../assets/images/images-card/lucio-wallpaper.jpg",
    name: "Marco Antônio",
    nick: "marconi696969 ",
    role: ["cardsup", "../assets/images/Icons/sup-rosa-semborda.png"],
    instagram: "#",
    date: "20/07/2029",
    city: "Ivoti/RS",
  },
];
