export const players = [
  {
    id: 1,
    imgHero: "../assets/images/images-card/zarya-wallpaper.png",
    name: "Leonardo Rezio",
    nick: "leorezio",
    role: ["cardtank", "../assets/images/Icons/tnk-azul-semborda.png"],
    instagram: "https://www.instagram.com/leorezio/",
    date: "29/12/2019",
    city: "Brasília/DF",
  },
  {
    id: 2,
    imgHero: "../assets/images/images-card/mercy-wallpaper.png",
    name: "Leandro Ferreira",
    nick: "lehboss",
    role: ["cardsup", "../assets/images/Icons/sup-rosa-semborda.png"],
    instagram: "https://www.instagram.com/xo_lehboss/",
    date: "Fundador",
    city: "São Paulo/SP",
  },
  {
    id: 3,
    imgHero: "../assets/images/images-card/mccree-wallpaper.jpg",
    name: "Daniel Sette",
    nick: "settedan",
    role: ["carddps", "../assets/images/Icons/dps-amarelo-semborda.png"],
    instagram: "https://www.instagram.com/danielsette/",
    date: "Co-Fundador",
    city: "São Paulo/SP",
  },
];
